In [1]:
#importing the dataset
import pandas as pd

df = pd.read_csv("C:/Users/IMAANI/Desktop/data/raw_dataset.csv")
df.head()

,acc_code,incident_datetime,report_datetime,province_en,agency,vehicle_type,presumed_cause,accident_type,number_of_vehicles_involved,number_of_fatalities,number_of_injuries,weather_condition,latitude,longitude,road_description,slope_description
0,571905,01/01/2019 00:00,01/02/2019 06:11,Loburi,department of rural roads,motorcycle,driving under the influence of alcohol,other,1,0,2,clear,14.959105,100.873463,straight road,no slope
1,3790870,01/01/2019 00:03,02/20/2020 13:48,Ubon Ratchathani,department of highways,private/passenger car,speeding,rollover/fallen on straight road,1,0,2,clear,15.210738,104.862689,straight road,no slope
2,599075,01/01/2019 00:05,01/01/2019 10:35,Prachuap Khiri Khan,department of highways,motorcycle,speeding,head-on collision (not overtaking),2,1,0,clear,12.374259,99.907949,wide curve,slope area
3,571924,01/01/2019 00:20,01/02/2019 05:12,Chiang Mai,department of rural roads,motorcycle,driving under the influence of alcohol,other,1,0,1,clear,18.601721,98.804204,straight road,no slope
4,599523,01/01/2019 00:25,01/04/2019 09:42,Nakhon Sawan,department of highways,private/passenger car,cutting in closely by people/vehicles/animals,rollover/fallen on straight road,1,0,0,clear,15.866389,100.590010,straight road,no slope

In [2]:
#Removing any missing values
print(df.isnull().sum())
df_clean = df.dropna()
print(df_clean.isnull().sum())
df_clean.head()

acc_code                         0
incident_datetime                0
report_datetime                  0
province_en                      0
agency                           0
vehicle_type                     0
presumed_cause                   0
accident_type                    0
number_of_vehicles_involved      0
number_of_fatalities             0
number_of_injuries               0
weather_condition                0
latitude                       359
longitude                      359
road_description                 0
slope_description                0
dtype: int64
acc_code                       0
incident_datetime              0
report_datetime                0
province_en                    0
agency                         0
vehicle_type                   0
presumed_cause                 0
accident_type                  0
number_of_vehicles_involved    0
number_of_fatalities           0
number_of_injuries             0
weather_condition              0
latitude                       0
longitude                      0
road_description               0
slope_description              0
dtype: int64

,acc_code,incident_datetime,report_datetime,province_en,agency,vehicle_type,presumed_cause,accident_type,number_of_vehicles_involved,number_of_fatalities,number_of_injuries,weather_condition,latitude,longitude,road_description,slope_description
0,571905,01/01/2019 00:00,01/02/2019 06:11,Loburi,department of rural roads,motorcycle,driving under the influence of alcohol,other,1,0,2,clear,14.959105,100.873463,straight road,no slope
1,3790870,01/01/2019 00:03,02/20/2020 13:48,Ubon Ratchathani,department of highways,private/passenger car,speeding,rollover/fallen on straight road,1,0,2,clear,15.210738,104.862689,straight road,no slope
2,599075,01/01/2019 00:05,01/01/2019 10:35,Prachuap Khiri Khan,department of highways,motorcycle,speeding,head-on collision (not overtaking),2,1,0,clear,12.374259,99.907949,wide curve,slope area
3,571924,01/01/2019 00:20,01/02/2019 05:12,Chiang Mai,department of rural roads,motorcycle,driving under the influence of alcohol,other,1,0,1,clear,18.601721,98.804204,straight road,no slope
4,599523,01/01/2019 00:25,01/04/2019 09:42,Nakhon Sawan,department of highways,private/passenger car,cutting in closely by people/vehicles/animals,rollover/fallen on straight road,1,0,0,clear,15.866389,100.590010,straight road,no slope

In [3]:
#Removing duplicates
print(df.duplicated().sum())
df_clean = df.drop_duplicates()
print(df_clean.duplicated().sum())
df_clean.head()

0
0

,acc_code,incident_datetime,report_datetime,province_en,agency,vehicle_type,presumed_cause,accident_type,number_of_vehicles_involved,number_of_fatalities,number_of_injuries,weather_condition,latitude,longitude,road_description,slope_description
0,571905,01/01/2019 00:00,01/02/2019 06:11,Loburi,department of rural roads,motorcycle,driving under the influence of alcohol,other,1,0,2,clear,14.959105,100.873463,straight road,no slope
1,3790870,01/01/2019 00:03,02/20/2020 13:48,Ubon Ratchathani,department of highways,private/passenger car,speeding,rollover/fallen on straight road,1,0,2,clear,15.210738,104.862689,straight road,no slope
2,599075,01/01/2019 00:05,01/01/2019 10:35,Prachuap Khiri Khan,department of highways,motorcycle,speeding,head-on collision (not overtaking),2,1,0,clear,12.374259,99.907949,wide curve,slope area
3,571924,01/01/2019 00:20,01/02/2019 05:12,Chiang Mai,department of rural roads,motorcycle,driving under the influence of alcohol,other,1,0,1,clear,18.601721,98.804204,straight road,no slope
4,599523,01/01/2019 00:25,01/04/2019 09:42,Nakhon Sawan,department of highways,private/passenger car,cutting in closely by people/vehicles/animals,rollover/fallen on straight road,1,0,0,clear,15.866389,100.590010,straight road,no slope

In [4]:
#Correcting data types

#--Current data types--
print(df_clean.dtypes)

acc_code                         int64
incident_datetime                  str
report_datetime                    str
province_en                        str
agency                             str
vehicle_type                       str
presumed_cause                     str
accident_type                      str
number_of_vehicles_involved      int64
number_of_fatalities             int64
number_of_injuries               int64
weather_condition                  str
latitude                       float64
longitude                      float64
road_description                   str
slope_description                  str
dtype: object

In [5]:
#Converting data types
df_clean['incident_datetime'] = pd.to_datetime(df['incident_datetime'])
df_clean['report_datetime'] = pd.to_datetime(df['report_datetime'])

print(df_clean.dtypes)

acc_code                                int64
incident_datetime              datetime64[us]
report_datetime                datetime64[us]
province_en                               str
agency                                    str
vehicle_type                              str
presumed_cause                            str
accident_type                             str
number_of_vehicles_involved             int64
number_of_fatalities                    int64
number_of_injuries                      int64
weather_condition                         str
latitude                              float64
longitude                             float64
road_description                          str
slope_description                         str
dtype: object

In [8]:
#Renaming columns
df_clean.rename(columns={'incident_datetime': 'Incident DateTime', 
                         'report_datetime': 'Report DateTime',
                        'incident_location': 'Incident Location',
                        'incident_type': 'Incident Type',
                        'description': 'Description',
                        'reported_by': 'Reported By',
                        'province_en':'Province',
                        'slope_description':'Slope Description',
                        'road_description':'Road Description',
                        'vehicle_type':'Vehicle Type',
                        'presumed_cause':'Presumed Cause',
                        'accident_type':'Accident Type',
                        'number_of_vehicles_involved':'No. Vehicles Involved',
                        'number_of_fatalities':'No. Fatalities',
                        'number_of_injuries':'No. Injuries',
                        'weather_condition':'Weather Conditions',
                    
                    

                         
                         }, inplace=True)

In [9]:
#Save cleaned dataset
df_clean.to_csv("C:/Users/IMAANI/Desktop/data/cleaned_dataset.csv", index=False)
df = pd.read_csv("C:/Users/IMAANI/Desktop/data/cleaned_dataset.csv")
df.head()

,acc_code,Incident DateTime,Report DateTime,Province,agency,Vehicle Type,Presumed Cause,Accident Type,No. Vehicles Involved,No. Fatalities,No. Injuries,Weather Conditions,latitude,longitude,Road Description,Slope Description
0,571905,2019-01-01 00:00:00,2019-01-02 06:11:00,Loburi,department of rural roads,motorcycle,driving under the influence of alcohol,other,1,0,2,clear,14.959105,100.873463,straight road,no slope
1,3790870,2019-01-01 00:03:00,2020-02-20 13:48:00,Ubon Ratchathani,department of highways,private/passenger car,speeding,rollover/fallen on straight road,1,0,2,clear,15.210738,104.862689,straight road,no slope
2,599075,2019-01-01 00:05:00,2019-01-01 10:35:00,Prachuap Khiri Khan,department of highways,motorcycle,speeding,head-on collision (not overtaking),2,1,0,clear,12.374259,99.907949,wide curve,slope area
3,571924,2019-01-01 00:20:00,2019-01-02 05:12:00,Chiang Mai,department of rural roads,motorcycle,driving under the influence of alcohol,other,1,0,1,clear,18.601721,98.804204,straight road,no slope
4,599523,2019-01-01 00:25:00,2019-01-04 09:42:00,Nakhon Sawan,department of highways,private/passenger car,cutting in closely by people/vehicles/animals,rollover/fallen on straight road,1,0,0,clear,15.866389,100.590010,straight road,no slope